services:
  opensearch:
    image: opensearchproject/opensearch:3.2.0
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyAdm1n_Passw0rd!
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - plugins.security.ssl.http.enabled=false     # <-- allow plain HTTP on :9200
    ports:
      - "9200:9200"
      - "9600:9600"

  dashboards:
    image: opensearchproject/opensearch-dashboards:3.2.0
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"] # stays http
    depends_on:
      - opensearch
    ports:
      - "5601:5601"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped

  ollama-pull-models:
    image: curlimages/curl:latest
    depends_on:
      - ollama
    command: >
      sh -c "
        echo 'Waiting for Ollama service to be ready...' &&
        sleep 20 &&
        echo 'Pulling granite3.3:2b model...' &&
        curl -X POST http://ollama:11434/api/pull -H 'Content-Type: application/json' -d '{\"name\": \"granite3.3:2b\"}' &&
        echo 'Pulling embeddinggemma:300m embedding model...' &&
        curl -X POST http://ollama:11434/api/pull -H 'Content-Type: application/json' -d '{\"name\": \"embeddinggemma:300m\"}' &&
        echo 'Models pulled successfully!' &&
        curl -X GET http://ollama:11434/api/tags
      "
    restart: "no"

  docling-serve:
    image: quay.io/docling-project/docling-serve:latest
    ports:
      - "5001:5001"
    environment:
      - DOCLING_SERVE_ENABLE_UI=1
      - DOCLING_SERVE_MAX_SYNC_WAIT=600
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  ollama_data:
