services:
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=MyAdm1n_Passw0rd!
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - plugins.security.ssl.http.enabled=false     # <-- allow plain HTTP on :9200
    ports:
      - "9200:9200"
      - "9600:9600"

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"] # stays http
    depends_on:
      - opensearch
    ports:
      - "5601:5601"
