import { StyleSheet, Platform } from 'react-native';

export const HomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  chatContainer: {
    flex: 1,
  },
  messagesContainer: {
    paddingHorizontal: 12,
    paddingBottom: 12,
    backgroundColor: '#f5f5f5',
  },
  input: {
    color: '#000',
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    margin: 8,
    fontSize: 16,
    width: '100%',
    boxSizing: 'border-box',
    borderWidth: 1,
    borderColor: '#ddd',
  },
  sendContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
    height: undefined,
  },
  dropdownContainer: {
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  pickerWrapper: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
    overflow: 'hidden',
    minHeight: 48,
  },
  picker: {
    color: '#000',
    backgroundColor: 'transparent',
    borderRadius: 8,
    fontSize: 16,
    height: 48,
  },
  clearButton: {
    backgroundColor: '#ff6b6b',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 70,
  },
  clearButtonDisabled: {
    backgroundColor: '#ccc',
    opacity: 0.5,
  },
  clearButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  usernameContainer: {
    marginBottom: 4,
    marginLeft: 10,
  },
  usernameText: {
    color: '#666',
    fontSize: 12,
    fontWeight: '600',
  },
  loadingContainer: {
    padding: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  loadingBarsContainer: {
    marginLeft: 8,
  },
  loadingBar1: {
    width: 40,
    height: 8,
    backgroundColor: '#e0e0e0',
    borderRadius: 4,
    marginBottom: 4,
  },
  loadingBar2: {
    width: 60,
    height: 8,
    backgroundColor: '#e0e0e0',
    borderRadius: 4,
  },
  messageTextContainer: {
    padding: 8,
  },
  messageContainer: {
    marginLeft: 0,
    marginRight: 0,
    paddingLeft: 0,
    paddingRight: 0,
    alignItems: 'flex-start',
  },
  chatIcon: {
    marginRight: 4,
  },
  localModeIndicator: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#e8f5e9',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 8,
  },
  localModeText: {
    color: '#2e7d32',
    fontSize: 14,
    fontWeight: '600',
  },
  toggleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 8,
  },
  toggleLabel: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  warningBanner: {
    backgroundColor: '#fff3cd',
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#ffc107',
  },
  warningText: {
    color: '#856404',
    fontSize: 13,
    flex: 1,
  },
  downloadBanner: {
    backgroundColor: '#e3f2fd',
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#2196F3',
    flexWrap: 'wrap',
  },
  downloadText: {
    color: '#0d47a1',
    fontSize: 13,
    flex: 1,
  },
  progressBar: {
    width: '100%',
    height: 4,
    backgroundColor: '#bbdefb',
    borderRadius: 2,
    marginTop: 8,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#2196F3',
    borderRadius: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    width: '100%',
    maxWidth: 640,
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginTop: 12,
    color: '#0d47a1',
  },
  modalMessage: {
    fontSize: 14,
    color: '#333',
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 12,
  },
  modalProgressText: {
    fontSize: 13,
    color: '#0d47a1',
    marginTop: 8,
    textAlign: 'center',
  },
  modalButtonsRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 12,
  },
  modalButton: {
    backgroundColor: '#2196F3',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    minWidth: 110,
    alignItems: 'center',
  },
  modalButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  upgradeButton: {
    marginLeft: 12,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
  },
  upgradeButtonText: {
    display: 'none',
  },
  modalFullWidth: {
    width: '100%',
  },
  inlineStrong: {
    fontWeight: '700',
  },
});

export const bubbleStyles = {
  wrapperStyle: {
    left: {
      backgroundColor: '#e3f2fd',
      borderWidth: 1,
      borderColor: '#2196f3',
      marginLeft: 0,
      marginRight: 0,
    },
    right: {
      backgroundColor: '#e3f2fd',
      borderWidth: 1,
      borderColor: '#2196f3',
      marginLeft: 0,
      marginRight: 0,
    },
  },
  textStyle: {
    left: { color: '#222' },
    right: { color: '#222' },
  },
  containerToNextStyle: {
    left: { marginBottom: 20, alignSelf: 'flex-start' as const },
    right: { marginBottom: 20, alignSelf: 'flex-start' as const },
  },
  containerToPreviousStyle: {
    left: { marginBottom: 20, alignSelf: 'flex-start' as const },
    right: { marginBottom: 20, alignSelf: 'flex-start' as const },
  },
  containerStyle: {
    left: { marginLeft: 0, marginRight: 0, alignItems: 'flex-start' as const },
    right: { marginLeft: 0, marginRight: 0, alignItems: 'flex-start' as const },
  },
};

export const userBubbleStyles = {
  wrapperStyle: {
    left: {
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: '#e0e0e0',
      marginLeft: 0,
      marginRight: 0,
    },
    right: {
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: '#e0e0e0',
      marginLeft: 0,
      marginRight: 0,
    },
  },
  textStyle: {
    left: { color: '#222' },
    right: { color: '#222' },
  },
  containerToNextStyle: {
    left: { marginBottom: 20, alignSelf: 'flex-start' as const },
    right: { marginBottom: 20, alignSelf: 'flex-start' as const },
  },
  containerToPreviousStyle: {
    left: { marginBottom: 20, alignSelf: 'flex-start' as const },
    right: { marginBottom: 20, alignSelf: 'flex-start' as const },
  },
  containerStyle: {
    left: { marginLeft: 0, marginRight: 0, alignItems: 'flex-start' as const },
    right: { marginLeft: 0, marginRight: 0, alignItems: 'flex-start' as const },
  },
};

export const markdownStyles = {
  assistant: {
    body: { color: '#222', fontSize: 16 },
    code_inline: {
      backgroundColor: '#f0f0f0',
      color: '#d63384',
      paddingHorizontal: 4,
      paddingVertical: 2,
      borderRadius: 3,
      fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    },
    code_block: {
      backgroundColor: '#f6f8fa',
      color: '#24292e',
      padding: 10,
      borderRadius: 6,
      fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    },
    fence: {
      backgroundColor: '#f6f8fa',
      color: '#24292e',
      padding: 10,
      borderRadius: 6,
      fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    },
    strong: { fontWeight: 'bold' as const },
    em: { fontStyle: 'italic' as const },
    link: { color: '#0366d6', textDecorationLine: 'underline' as const },
    blockquote: {
      backgroundColor: '#f6f8fa',
      borderLeftColor: '#dfe2e5',
      borderLeftWidth: 4,
      paddingLeft: 10,
      marginLeft: 0,
    },
    list_item: { flexDirection: 'row' as const, marginBottom: 4 },
    bullet_list: { marginBottom: 8 },
    ordered_list: { marginBottom: 8 },
    heading1: { fontSize: 24, fontWeight: 'bold' as const, marginBottom: 8 },
    heading2: { fontSize: 20, fontWeight: 'bold' as const, marginBottom: 6 },
    heading3: { fontSize: 18, fontWeight: 'bold' as const, marginBottom: 4 },
  },
  user: {
    body: { color: '#222', fontSize: 16 },
    code_inline: {
      backgroundColor: '#f0f0f0',
      color: '#d63384',
      paddingHorizontal: 4,
      paddingVertical: 2,
      borderRadius: 3,
    },
  },
};
